name: Push
on: 
  push:
    branches:
      - '**'
  pull_request:

jobs:
  dynamic:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build
      uses: nzbr/vlang-action@v1
      with:
        args: -o vlogsolv 

    - name: Prepare artifact upload
      run: |
        set -e
        mkdir build
        cp -r vlogsolv LICENSE README.md build/

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: vlogsolv
        path: build
