name: Release
on:
  push:
    tags:
      - '**'

jobs:
  dynamic:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Build
      uses: nzbr/vlang-action@v2
      with:
        args: -o vlogsolv -prod -autofree -cc gcc

    - name: Prepare artifact upload
      run: |
        set -e
        mkdir build
        cp -r vlogsolv LICENSE README.md build/

    - name: Upload artifacts
      uses: actions/upload-artifact@main
      with:
        name: vlogsolv
        path: build

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [dynamic]
    steps:
      - name: Install Dependencies
        run: |
          set -e
          sudo apt-get update && sudo apt-get install -y zip
      - name: Download Dynamic
        uses: actions/download-artifact@master
        with:
          name: vlogsolv
          path: vlogsolv
      - name: Zip
        run: |
          set -e
          zip -r vlogsolv.zip vlogsolv
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: vlogsolv.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
